[package]
name        = "rsmt"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
sha2.workspace       = true
blake2.workspace     = true
thiserror.workspace  = true
rayon.workspace      = true

[[bench]]
name    = "smt"
harness = false

[dev-dependencies]
criterion.workspace = true
