[package]
name = "smt-store"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
rsmt.workspace       = true
rocksdb.workspace    = true
anyhow.workspace     = true
tracing.workspace    = true
hex.workspace        = true
thiserror.workspace  = true
rayon.workspace      = true

[[bench]]
name    = "store"
harness = false

[dev-dependencies]
tempfile.workspace  = true
criterion.workspace = true
